USE codeup_test_db;
INSERT INTO albums (artist, name, release_date, genre, sales)
VALUES ('Michael Jackson', 'Thriller', 1982, 'Pop, Funk, Rock', 51.2),
       ('AC/DC', 'Back in Black', 1980, 'Hard Rock', 30.1),
       ('Whitney Houston', 'The Bodyguard', 1992, 'R&B, Soul, Pop', 28.7),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 'Progressive Rock', 24.8),
       ('Eagles','The Greatest Hits', 1976, 'Country Rock, Soft Rock, Folk Rock', 41.2),
       ('Eagles', 'Hotel California', 1976, 'Soft Rock', 31.8),
       ('Shania Twain', 'Come On Over', 1997, 'Country Pop', 30.4),
       ('Fleetwood Mac', 'Rumours', 1977, 'Soft Rock', 29.3),
       ('Bee Gees', 'Saturday Night Fever', 1977, 'Disco', 22.1),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 'Hard Rock, Heavy Metal, Folk Rock', 30.4),
       ('Michael Jackson', 'Bad', 1987, 'Pop, Rhythm & Blues', 21.1),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 'Hard Rock, Glam Rock, Progressive Rock', 22),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 'Alternative Rock', 25.4),
       ('Bill Medley','Dirty Dancing', 1987, 'Pop, Rock, R&B', 24.1),
       ('Celine Dion','Falling into You', 1996, 'Pop, Soft Rock', 21.1),
       ('Adele','21', 2011, 'Pop, Soul', 27.1),
       ('The Beatles', '1', 2000, 'Rock', 23.2),
       ('Metallica', 'Metallica', 1991, 'Heavy Metal', 22.7),
       ('Celine Dion','Let''s Talk About Love', 1997, 'Pop, Soft Rock', 19.5),
       ('Bob Marley & The Wailers','Legend: The Best of Bob Marley & The Wailers', 1984, 'Reggae', 22.9),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 'Hard Rock',22.8),
       ('Bruce Springsteen','Born in the U.S.A.', 1984, 'Heartland Rock', 22),
       ('ABBA', 'Gold: Greatest Hits', 1992, 'Pop, Disco', 21.6),
       ('Dire Straits','Brothers in Arms', 1985, 'Roots Rock, Blues Rock, Soft Rock', 21.1),
       ('Santana', 'SuperNatural', 1999, 'Latin Rock', 20.8),
       ('Madonna', 'The Immaculate Collection', 1990, 'Pop, Dance', 19.8),
       ('Pink Floyd','The Wall', 1979, 'Progressive Rock', 18.9),
       ('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band', 1967, 'Rock', 18.3),
       ('Michael Jackson','Dangerous', 1991, 'New Jack Swing, R&B, Pop', 17),
       ('The Beatles', 'Abbey Road', 1969, 'Rock', 16.9);